[project]
name = "pretraining"
version = "0.1.0"
description = "Pretraining architectures implemented from scratch in PyTorch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "dataset",
    "datasets>=5.0.1",
    "einops>=0.8.2",
    "hf>=1.25.1",
    "matplotlib>=3.11.1",
    "nbformat>=5.10.4",
    "nbimporter>=0.3.4",
    "numpy>=2.5.1",
    "torch>=2.13.0",
    "transformers>=5.14.1",
]
